server:
  port: 8080
spring:
  application:
    name: notrash
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:file:/home/lucasbrandao/Documents/AM/no-trash/h2/NoTrashBD
    username: sa
    password: password
    driver-class-name: org.h2.Driver